name: MongoDB Compass

on:
  workflow_dispatch:

permissions:
  contents: write  # Allows pushing tags and uploading releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag name
        id: tag
        run: echo "TAG_NAME=v1.0.0" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and push Git tag if not exists
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
            echo "Tag $TAG_NAME already exists in the remote. Skipping tag creation."
          else
            git tag $TAG_NAME
            git push origin $TAG_NAME
          fi

      - name: Download MongoDB Installer
        run: |
          curl -L -o MongoDB-User-8.0.11.exe \
          https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-8.0.11.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: Cursor-Windows-x64-User-1.0.0.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
